### model
model_name_or_path: llm-jp/llm-jp-3-3.7b

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: aya_evolved_it0
template: alpaca_ja
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/full/sft/evol_it0
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### logging
report_to: wandb
project: "auto-evol-instruct"
run_name: "llm-jp-3-3.7b-evol-it0"